### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by volands** [agios/docker-postgres-bdr#1]
Hello Alexandros,

I try to use your dockerimage "docker-postgres-bdr". If I start to build with "docker build .", i Run into this error message:

[...]
Setting up libcurl3:amd64 (7.38.0-4+deb8u3) ...
Setting up krb5-locales (1.12.1+dfsg-19+deb8u2) ...
Setting up openssl (1.0.1k-3+deb8u2) ...
Setting up ca-certificates (20141019+deb8u1) ...
Setting up curl (7.38.0-4+deb8u3) ...
Setting up libsasl2-modules:amd64 (2.1.26.dfsg1-13+deb8u1) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   583    0   583    0     0   1433      0 --:--:-- --:--:-- --:--:--  1435
100 2091k  100 2091k    0     0   848k      0  0:00:02  0:00:02 --:--:-- 1137k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   591    0   591    0     0   1402      0 --:--:-- --:--:-- --:--:--  1400
100   543  100   543    0     0    497      0  0:00:01  0:00:01 --:--:--   497
gpg: directory `/root/.gnupg' created
gpg: new configuration file`/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring`/root/.gnupg/pubring.gpg' created
gpg: assuming signed data in `/usr/local/bin/gosu'
gpg: Signature made Wed Nov 19 07:57:11 2014 UTC using RSA key ID BF357DD4
gpg: Can't check signature: public key not found
INFO[0020] The command [/bin/sh -c apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/\*   && curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)"   && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc"   && gpg --verify /usr/local/bin/gosu.asc   && rm /usr/local/bin/gosu.asc   && chmod +x /usr/local/bin/gosu   && apt-get purge -y --auto-remove curl] returned a non-zero code: 2

Hope you can help or have an idea in context of this problem...
Thanks and best regards,
Patrick

**Comment by agios** [comment]
Hi @volands 

I cannot see your whole run, but I suspect something went wrong in Step 4, which should have downloaded the key reported missing in your message in Step 5...

Another thing that would need changing is to update to the latest BDR release, just commited it, so try pulling the latest version too.

**Comment by volands** [comment]
Thank you for your reply! I think the problem was on my side - after a new pull and build I now can run your image. In actual fact this issue can be closed.

Perhabs I can use this occasion to ask a second question: I now try to use SSL for the Postgres/BDR port (to encrypt the transfer/connection). On the basis of this script:
https://github.com/aptible/docker-postgresql/blob/master/bin/run-database.sh
I have added the certificate generation and the change of pg_hba.conf and postgresql.conf (overall only three little changes). On run (also after a complete new build) I stuck on this message - which is not yet completely clear to me.

$ docker run -e POSTGRES_PASSWORD=password aa164d89deb0
Generating a 2048 bit RSA private key
...................+++
.....+++
writing new private key to 'server.key'
 -
postgres cannot access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory

Here is my actual version - I try to continue to solve the problem:
https://github.com/volands/docker-postgres-bdr/blob/master/docker-entrypoint.sh
Maybe you have an idea or have already carried out this procedure in the past...

**Comment by volands** [comment]
Hi @agios 

I could now create a first SSL-configuration example - it is very q&d, but perhabs you can use this for your branch:
https://github.com/volands/docker-postgres-bdr/

Thanks and best regards!
