### ISSUE TITLE
Ready for Docker Swarm?

### ISSUE THREAD

**Issue by pascalandy** [agios/docker-postgres-bdr#2]
Would be so curious to try this on a docker swarm using:

`docker service ...`

Also a docker-compose v2 template would be great :)

Cheers!

**Comment by pozgo** [comment]
Hi @pascalandy , I have done something like that for docker-compose :) 
Thanks @agios for inspiration 

[https://github.com/pozgo/docker-postgres-bdr](https://github.com/pozgo/docker-postgres-bdr)

**Comment by pascalandy** [comment]
Sounds great!! Thanks for buzzing me :)

**Comment by agios** [comment]
Good to hear this was useful!

We ended up using a different solution, so this role is not actively maintained anymore

**Comment by pozgo** [comment]
@agios out of curiosity. What did you choose to use for replication in docker? 

I'm developing some more advanced way of replicating database for Gitlab which doesn't have any HA solution for the database.

**Comment by agios** [comment]
@pozgo this project had specific updates with low frequency, so this was handled on the application level, the updates are tracked initially in a clustered Redis and from there there is a job which makes sure that the updates have been performed on each DB.

On another project with much higher replication requirements we have gone with SymmetricDS. A pain to configure initially, but very scalable and can be clustered.
